version: '3.8'
services:
  mongodb:
    image: mongo:4.4.6-bionic
    container_name: mongodb
    hostname: server-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    volumes:
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
      - mongo-data:/data/db
    command: mongod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  mongo-data:
